# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /kallen-api

swagger:
  enable: true

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  datasource:
    # Mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.68.188.195:3306/kallen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 1
    host: 81.68.188.195
    port: 6379
    password: 123456
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms   # 连接池最大阻塞等待是时间（使用负值表示没有限制）
        max-idle: 10     # 连接池中的最大空闲连接
        min-idle: 5      # 连接池中的最小空闲连接