# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /kallen-api

swagger:
  enable: true

spring:
  datasource:
    # Mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.68.188.195:3306/kallen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss